version: '3'

services:
  accrualpostgres:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=accrual
    ports:
      - '5432:5432'
    networks:
      - mainnetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  gophermartpostgres:
    image: 'bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=postgres
      - POSTGRESQL_DATABASE=gophermart
    ports:
      - '5433:5432'
    networks:
      - mainnetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  gophermart:
    depends_on:
      gophermartpostgres:
        condition: service_healthy
    build:
      dockerfile: ./Dockerfile.Gophermart
      context: ../
    networks:
      - mainnetwork
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=${gophermartLogLevel}
      - RUN_ADDRESS=${gophermartRunAddress}
      - DATABASE_URI=${gophermartDBURI}
      - ACCRUAL_SYSTEM_ADDRESS=${accrualAddress}
      - SECRET_KEY_PATH=${secretKeyPath}
      - TOKEN_TTL=${tokenTTL}

  accrual:
    depends_on:
      accrualpostgres:
        condition: service_healthy
    build: 
      dockerfile: ./Dockerfile.Accrual
      context: ../
    networks:
      - mainnetwork
    ports:
      - "8081:8081"
    environment:
      - LOG_LEVEL=${accrualLogLevel}
      - RUN_ADDRESS=${accrualRunAddress}
      - DATABASE_URI=${accrualDBURI}
    

networks:
  mainnetwork:
    driver: bridge
